name: pr action
on: 
  workflow_dispatch:
    inputs:
      source:
        description: 'Define env name'     
        required: true
      dest:
        description: 'Define branch name'     
        required: true
        
jobs:
 
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - run: |
        echo "source: ${{ github.event.inputs.source }}" 
        echo "dest: ${{ github.event.inputs.dest }}"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
          destination_branch: ${{ github.event.inputs.source }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"

