name: pr action
on: 
  workflow_dispatch:
    inputs:
      source:
        description: 'Define env name'     
        required: true
      dest:
        description: 'Define branch name'     
        required: true
        
jobs:
 
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.source }}" 
        echo "Branch: ${{ github.event.inputs.dest }}"
