name: pr action
on: 
  workflow_dispatch:
    inputs:
      source:
        description: 'Define env name'     
        required: true
      dest:
        description: 'Define branch name'     
        required: true
        
jobs:
 
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - run: |

        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        --url https://api.github.com/${{ github.repository }}/pulls \
        -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat: ${{ github.event.inputs.source }}","base":" ${{ github.event.inputs.dest }}"}'
    

